---
name: jmlntw/ubuntu-mirror

on:
  push:
    branches:
      - main
    paths:
      - ubuntu-mirror/**
  schedule:
    - cron: 21 2 21 * *

jobs:
  docker:
    name: Docker Image CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ubuntu-mirror/xenial
            platforms: |
              linux/386
              linux/amd64
              linux/arm
              linux/arm64
            tags: |
              jmlntw/ubuntu-mirror:16.04
              jmlntw/ubuntu-mirror:xenial
          - context: ubuntu-mirror/bionic
            platforms: |
              linux/386
              linux/amd64
              linux/arm
              linux/arm64
            tags: |
              jmlntw/ubuntu-mirror:18.04
              jmlntw/ubuntu-mirror:bionic
          - context: ubuntu-mirror/focal
            platforms: |
              linux/amd64
              linux/arm
              linux/arm64
            tags: |
              jmlntw/ubuntu-mirror:20.04
              jmlntw/ubuntu-mirror:focal
              jmlntw/ubuntu-mirror:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ matrix.tags }}
          push: true
