---
name: "image: ubuntu-mirror"

on:
  push:
    branches:
      - main
    paths:
      - ubuntu-mirror/**
  schedule:
    # At 03:00 on day-of-month 1 in every 3rd month.
    - cron: '0 3 1 */3 *'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ubuntu-mirror/xenial
            tags:
              - jmlntw/ubuntu-mirror:xenial
              - jmlntw/ubuntu-mirror:16.04
          - context: ubuntu-mirror/bionic
            tags:
              - jmlntw/ubuntu-mirror:bionic
              - jmlntw/ubuntu-mirror:18.04
          - context: ubuntu-mirror/focal
            tags:
              - jmlntw/ubuntu-mirror:focal
              - jmlntw/ubuntu-mirror:20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          platforms: linux/386,linux/amd64,linux/arm,linux/arm64
          push: true
          tags: ${{ join(matrix.tags, ',') }}
