---
name: "image: ubuntu-taiwanize"

on:
  push:
    branches:
      - main
    paths:
      - ubuntu-taiwanize/**
  schedule:
    # At 05:00 on day-of-month 1 in every 3rd month.
    - cron: '0 5 1 */3 *'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ubuntu-taiwanize/xenial
            platforms:
              - linux/386
              - linux/amd64
              - linux/arm
              - linux/arm64
            tags:
              - jmlntw/ubuntu-taiwanize:xenial
              - jmlntw/ubuntu-taiwanize:16.04
          - context: ubuntu-taiwanize/bionic
            platforms:
              - linux/386
              - linux/amd64
              - linux/arm
              - linux/arm64
            tags:
              - jmlntw/ubuntu-taiwanize:bionic
              - jmlntw/ubuntu-taiwanize:18.04
          - context: ubuntu-taiwanize/focal
            platforms:
              - linux/amd64
              - linux/arm
              - linux/arm64
            tags:
              - jmlntw/ubuntu-taiwanize:focal
              - jmlntw/ubuntu-taiwanize:20.04
              - jmlntw/ubuntu-taiwanize:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          platforms: ${{ join(matrix.platforms, ',') }}
          push: true
          tags: ${{ join(matrix.tags, ',') }}
